### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by xivk** [openplannerteam/hopper#1]
When trying to set this up we get this message:

```
./src/screens/LocationSearchScreen/style.module.scss (./node_modules/react-scripts/node_modules/css-loader/dist/cjs.js??ref--6-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-6-3!./node_modules/react-scripts/node_modules/sass-loader/lib/loader.js??ref--6-oneOf-6-4!./src/screens/LocationSearchScreen/style.module.scss)
Module not found: Can't resolve '../../assets/images/brand-delijn.svg' in '/data/work/openplannerteam/hopper/src/screens/LocationSearchScreen'
```

And yes, this file is not there. How can we fix this?

**Comment by xivk** [comment]
With a closer look, it seems all the brand-*svgs are missing.

**Comment by mathieudelvaux** [comment]
Hi @xivk! I'm so sorry for this.
Right before release, I removed files that should've been unused and made the assumption that it would still work.
Turns out there was some leftover CSS code that tried to import those said files.
I cleaned the build and made a PR (#2) that closes this issue: I'll let you merge it 🙂

**Comment by xivk** [comment]
No worries, thanks! :+1:
